# Generated by Django 5.1.1 on 2024-09-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servey", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profileform",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="profileform",
            name="last_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profileform",
            name="office_location",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
