# Generated by Django 5.1.1 on 2024-09-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("servey", "0002_rename_name_profileform_first_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profileform",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="profileform",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="profileform",
            name="office_location",
        ),
    ]
