# Generated by Django 5.1.1 on 2024-09-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servey", "0003_rename_first_name_profileform_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("office", models.CharField(max_length=100)),
                ("quote", models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name="ProfileForm",
        ),
    ]
